Rails/Projekte/ontrack/config/routes.rb
Rails.application.routes.draw do
  
  
  root 'projects#index'

  resources :projects do
    resources :tasks
  end
  

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

Rails/Projekte/ontrack/app/models/project.rb
class Project < ActiveRecord::Base

	has_many :tasks
	
	validates :title, length: { minimum: 5}
	validate :start_date_validation

	def start_date_validation
		if start_date.present? && start_date < Date.today
			errors.add(:start_date, ' kann nicht in der Vergangenheit liegen')
		end
	end

end

Rails/Projekte/ontrack/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

Rails/Projekte/ontrack/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/Projekte/ontrack/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:edit, :show, :destroy, :update]
	def index
		@projects = Project.all
	end

	def show

	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(projects_params)
		if @project.save
			redirect_to root_path, notice: "Erfolgreich gespeichert"
		else
			render "new"
		end
	end

	def edit

	end

	def update
		if @project.update(projects_params)
			redirect_to projects_path, notice: "Update erfolgreich"
		else
			render 'edit'
		end
	end

	def destroy
		@project.delete
		redirect_to projects_path, notice: "Projekt: #{@project.title} wurde geloescht."
	end

	private
		def set_project
			@project = Project.find(params[:id])
		end

		def projects_params
			params.require(:project).permit(:title, :description, :start_date)
		end
end

Rails/Projekte/ontrack/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :start_date, :end_date, :project_id_id)
    end
end

Rails/Projekte/ontrack/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/Projekte/ontrack/app/helpers/projects_helper.rb
module ProjectsHelper
end

Rails/Projekte/ontrack/app/helpers/tasks_helper.rb
module TasksHelper
end

Rails/Projekte/ontrack/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

Rails/Projekte/ontrack/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

Rails/Projekte/ontrack/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

Rails/Projekte/ontrack/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ontrack" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ontrack" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

Rails/Projekte/ontrack/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>

	<%= render "shared/errors", object: @project %>

	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :title %>
		</div>
		<div class="medium-9 columns">
			<%= f.text_field :title %>
		</div>
	</div>

	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :description %>
		</div>
		<div class="medium-9 columns">
			<%= f.text_area :description %>
		</div>
	</div>

	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :start_date %>
		</div>
		<div class="medium-9 columns">
			<%= f.date_select :start_date %>
		</div>
	</div>

	<div class="row">
		<div class="medium-3 columns">&nbsp;</div>
		<div class="medium-9 columns">
			<%= f.submit "Abschicken", class: "button" %>
			&nbsp;
			<%= link_to "Zurück", projects_path, class: "button" %>
		</div>
	</div>

<% end %>

Rails/Projekte/ontrack/app/views/projects/edit.html.erb
<h3>Projekt editieren</h3>

<%= render "form" %>

Rails/Projekte/ontrack/app/views/projects/index.html.erb
<h3>Listing Projekts</h3>

<table>
	<head>
		<tr>
			<td>Title</td>
			<td>Description</td>
			<td>Start Date</td>
			<td></td>
		</tr>
	</head>
	<body>
		<% @projects.each do |project| %>
			<tr>
				<td><%= project.title %></td>
				<td><%= project.description %></td>
				<td><%= project.start_date %></td>
				<td>
					<%= link_to "<i class='fi-eye'></i>".html_safe, project_path(project.id) %> | 
					<%= link_to "<i class='fi-pencil'></i>".html_safe, edit_project_path(project.id) %> | 
					<%= link_to "<i class='fi-trash'></i>".html_safe, project_path(project.id), method: :delete %>
				</td>
			</tr>
		<% end %>
	</body>

</table>

<%= link_to "Neues Projekt anlegen", new_project_path, class: "button" %>

Rails/Projekte/ontrack/app/views/projects/new.html.erb
<h3>Neues Projekt anlegen</h3>

<%= render "form" %>

Rails/Projekte/ontrack/app/views/projects/show.html.erb
<h3>Projekt: <%= @project.title %></h3>

<div class="panel">
	Startet am: <%= @project.start_date %>
	<hr />
	<%= @project.description %>
</div>

<%= link_to "Projekt Tasks anzeigen", project_tasks_path(@project) %>

Rails/Projekte/ontrack/app/views/shared/_errors.html.erb
	<% if object.errors.any? %>
		<div class="panel">
			<h3>Opps! Der <%= object.class.name.titleize.downcase %> konnte nicht gespeichert werden.</h3>
			Korrigieren Sie die folgenden <%= pluralize(object.errors.count, "error") %>:
			<ul>
				<% object.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>