Rails/Projekte/rails_app/config/routes.rb
Rails.application.routes.draw do
  
  root "events#index"
  get 'signup' => 'users#new'
  get 'signin' => "sessions#new"

  resource :session
  resources :users
  resources :events do
  	collection do
    	get 'past'
    	get 'upcoming'
    end
    resources :registrations
    resources :likes
  end
end

Rails/Projekte/rails_app/app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">

    <ul>
      <li><%= link_to "Alle Events", events_path %></li>
      <li class="has-dropdown">
        <a href="#">Event gefiltert</a>
        <ul class="dropdown">
          <li><%= link_to "Vergangene Events", past_events_path %></li>
        </ul>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.name, user_path(current_user.id) %></li>
        | 
        <li><%= link_to "SignOut", session_path, method: :delete %></li>
      <% else %>
      	<li><%= link_to "SignIn", signin_path %></li> | 
        <li><%= link_to "SignUp", signup_path %></li>
      <% end %>
    </ul>  
  </div>



  
</nav>

Rails/Projekte/rails_app/app/views/layouts/_sidebar.html.erb
<h4>Eventliste</h4>
<ul class="side-nav">
	<% @sidebar_events.each do |event| %>
		<li><%= link_to event.name, event_path(event.id) %></li>
	<% end %>
</ul>

Rails/Projekte/rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails App" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails App" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="row">
      <%= render 'layouts/navigation' %>
      <div class="row">
        <div class="medium-9 columns">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
        <div class="medium-3 columns">
          <%= render "layouts/sidebar" %>
        </div>
      </div>
  

    </div>
  
  </body>
</html>